uploading map to new relic
executing upload_map_file_to_new_relic
New Relic: map file upload attempt #1 (of 3)
Using URL: https://mobile-symbol-upload.eu01.nr-data.net
New Relic: map file upload attempt #2 (of 3)
Using URL: https://mobile-symbol-upload.eu01.nr-data.net
New Relic: map file upload attempt #3 (of 3)
Using URL: https://mobile-symbol-upload.eu01.nr-data.net
executing upload_dsym_to_new_relic
new relic: successfully uploaded dsym files
ts: '/Users/sameerkhan/Library/Developer/Xcode/DerivedData/InstaCover-cvttrzrqcorbikboxstoefcmvaav/Build/Intermediates.noindex/InstaCover.build/Debug-iphoneos/InstaCover.build/tmp'
New Relic: map file upload attempt #2 (of 3)
Using URL: https://mobile-symbol-upload.eu01.nr-data.net
Traceback (most recent call last):
  File "/Users/sameerkhan/Desktop/InstaCash Projects/InstaCover/Renew-Project/February-22/17:2:22/InstaCover/Pods/NewRelicAgent/NewRelic.xcframework/Resources/generateMap.py", line 96, in <module>
    os.mkdir(workDir)
OSError: [Errno 17] File exists: '/Users/sameerkhan/Library/Developer/Xcode/DerivedData/InstaCover-cvttrzrqcorbikboxstoefcmvaav/Build/Intermediates.noindex/InstaCover.build/Debug-iphoneos/InstaCover.build/tmp'
New Relic: map file upload attempt #3 (of 3)
Using URL: https://mobile-symbol-upload.eu01.nr-data.net
Traceback (most recent call last):
  File "/Users/sameerkhan/Desktop/InstaCash Projects/InstaCover/Renew-Project/February-22/17:2:22/InstaCover/Pods/NewRelicAgent/NewRelic.xcframework/Resources/generateMap.py", line 96, in <module>
    os.mkdir(workDir)
OSError: [Errno 17] File exists: '/Users/sameerkhan/Library/Developer/Xcode/DerivedData/InstaCover-cvttrzrqcorbikboxstoefcmvaav/Build/Intermediates.noindex/InstaCover.build/Debug-iphoneos/InstaCover.build/tmp'
executing upload_dsym_to_new_relic
new relic: successfully uploaded dsym files
